language: java
jdk:
  - oraclejdk8

sudo: false

env:
# These checkers complete in 50 min or less on the whole jdk.
  - GROUP=formatter
  - GROUP=index
  - GROUP=interning
  - GROUP=lock
  - GROUP=nullness
  - GROUP=regex
  - GROUP=signature
  - GROUP=value
script: ./.travis-build.sh $GROUP

git:
  depth: 3
